<?php


namespace app\facade;


use think\Facade;

class TestBoot extends Facade
{
    protected static function getFacadeClass()
    {
//        parent::getFacadeClass(); // TODO: Change the autogenerated stub
//        return \app\util\TestBoot::class;
        return 'test_boot';
    }
}